### DISCUSSION TITLE
How to package CLI tools in pex

### DISCUSSION THREAD

**Discussion by rpdelaney** [pex-tool/pex#2400] [Q&A] [answered]
For instance, this toy project [dumbpw](https://github.com/rpdelaney/dumbpw/). I define the entrypoint in pyproject.toml:

```toml
[tool.poetry.scripts]
dumbpw = "dumbpw.cli:cli"
```

However, if I run a pex archive, I get a python interpreter and not the dumbpw cli interface.

How might I do this with pex?
