### ISSUE TITLE
Processing pylock.toml fails to acknowledge downloaded dependency files with unusual characters

### ISSUE THREAD

**Issue by willtekulve-redwood** [pex-tool/pex#2772]
I am trying to create a pex file using `pylock.toml` that includes dependencies like PyYAML, Deprecated and ruamel.yaml. The logs appear to indicate the download successfully completes but a FileNotFoundError is raised. The filename in the download URL and the filename from the FileNotFoundError do not match.

An equivalent dependency list is successfully processed when using `requirements.txt` format.

```text
pex: Downloading FileArtifact(url=ArtifactURL(raw_url='https://internal-pypi/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.ma
nylinux2014_x86_64.whl', url_info=ParseResult(scheme='https', netloc='***', path='/***/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-manylinu
x_2_17_x86_64.manylinux2014_x86_64.whl', params='', query='', fragment=''), download_url='https://internal-pypi/simple/pyyaml/6.0.2/PyYAML-6.0.2-c
p312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', normalized_url='https://***/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-man
ylinux_2_17_x86_64.manylinux2014_x86_64.whl', scheme='https', path='/***/simple/pyyaml/6.0.
2/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', subdirectory=None, parameters
='', fragment_parameters={}, fingerprints=()), verified=False, fingerprint=Fingerprint(algorithm='sha256'
, hash='80bab7bfc629882493af4aa31a4cfa43a4c57c83813253626916b8c7ada83476'), filename='pyyaml-6.0.2-cp312-
cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'): 1158.4ms

FileNotFoundError: [Errno 2] No such file or directory: '/***/.cache/pex/downloads/1/80bab7
bfc629882493af4aa31a4cfa43a4c57c83813253626916b8c7ada83476.lck.work/pyyaml-6.0.2-cp312-cp312-manylinux_2_
17_x86_64.manylinux2014_x86_64.whl'
```

```text
pex: Downloading FileArtifact(url=ArtifactURL(raw_url='https://internal-pypi/simple/ruamel-yaml/0.18.10/ruamel.yaml-0.18.10-py3-none-any.whl', url
_info=ParseResult(scheme='https', netloc='***', p
ath='/***/simple/ruamel-yaml/0.18.10/ruamel.yaml-0.18.10-py3-none-any.whl', params='', quer
y='', fragment=''), download_url='https://internal-pypi/simple/ruamel-yaml/0.18.10/ruamel.yaml-0.18.10-py3-none-any.whl', normalized_url='https://internal-pypi/simple/ruamel-yaml/0.18.10/
ruamel.yaml-0.18.10-py3-none-any.whl', scheme='https', path='/internal-pypi/simple/ruamel-yaml/0.18.1
0/ruamel.yaml-0.18.10-py3-none-any.whl', subdirectory=None, parameters='', fragment_parameters={}, finger
prints=()), verified=False, fingerprint=Fingerprint(algorithm='sha256', hash='30f22513ab2301b3d2b577adc12
1c6471f28734d3d9728581245f1e76468b4f1'), filename='ruamel_yaml-0.18.10-py3-none-any.whl'): 1199.6ms

FileNotFoundError: [Errno 2] No such file or directory: '/***/.cache/pex/downloads/1/30f225
13ab2301b3d2b577adc121c6471f28734d3d9728581245f1e76468b4f1.lck.work/ruamel_yaml-0.18.10-py3-none-any.whl'
```

**Comment by jsirois** [comment]
@willtekulve-redwood is your output literal or redacted? I.E. Are the `***` literal? If so this would appear to be a bug dealing with a custom index with authentication via `~/.netrc` where Pex attempts to redact credentials in the custom index URL when present. This redaction is only supposed to occur in log output though, not in lock file output.

The more details you can provide about your setup the better of course.

**Comment by willtekulve-redwood** [comment]
The output is redacted. In total, I see 6 dependencies fail from my total list of ~100. Each failed dependency either includes capitalization or non alphanumeric characters (e.g. `.`) in it's PyPI package name.

**Comment by jsirois** [comment]
@willtekulve-redwood ok. Actually having a redacted pylock.toml would be helpful but I may be able to work our what's going on without that.

**Comment by jsirois** [comment]
A side-bar question: what are you using to generate the pylock.toml and how is doing this giving you an advantage over generating a hashed requirements.txt instead (assuming that is also a possibility). I'm generally interested in PEP-751 use cases that are not already satisfied by the requirements.txt psuedo-standard but I haven't run across a real one yet.

**Comment by willtekulve-redwood** [comment]
> what are you using to generate the pylock.toml

`uv export --format=pylock.toml`

> how is doing this giving you an advantage over generating a hashed requirements.txt instead (assuming that is also a possibility)

`pylock.toml` includes the index for each dependency. It makes me more confident that my CI tooling is correctly using our internal mirror rather than public PyPI.

> Actually having a redacted pylock.toml would be helpful but I may be able to work our what's going on without that.

Here's a partial one:

```toml
# This file was autogenerated by uv via the following command:
#    uv export --package redacted --no-dev --no-editable --no-emit-workspace --format=pylock.toml
lock-version = "1.0"
created-by = "uv"
requires-python = "==3.12.*"

[[packages]]
name = "aiofiles"
version = "24.1.0"
index = "https://redacted/simple/"
sdist = { url = "https://redacted/simple/aiofiles/24.1.0/aiofiles-24.1.0.tar.gz", hashes = { sha256 = "22a075c9e5a3810f0c2e48f3008c94d68c65d763b9b03857924c99e57355166c" } }
wheels = [{ url = "https://redacted/simple/aiofiles/24.1.0/aiofiles-24.1.0-py3-none-any.whl", hashes = { sha256 = "b4ec55f4195e3eb5d7abd1bf7e061763e864dd4954231fb8539a0ef8bb8260e5" } }]

[[packages]]
name = "pyyaml"
version = "6.0.2"
index = "https://redacted/simple/"
sdist = { url = "https://redacted/simple/pyyaml/6.0.2/pyyaml-6.0.2.tar.gz", hashes = { sha256 = "d584d9ec91ad65861cc08d42e834324ef890a082e591037abe114850ff7bbc3e" } }
wheels = [
    { name = "pyyaml-6.0.2-cp312-cp312-macosx_10_9_x86_64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-macosx_10_9_x86_64.whl", hashes = { sha256 = "c70c95198c015b85feafc136515252a261a84561b7b1d51e3384e0655ddf25ab" } },
    { name = "pyyaml-6.0.2-cp312-cp312-macosx_11_0_arm64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-macosx_11_0_arm64.whl", hashes = { sha256 = "ce826d6ef20b1bc864f0a68340c8b3287705cae2f8b4b1d932177dcc76721725" } },
    { name = "pyyaml-6.0.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hashes = { sha256 = "1f71ea527786de97d1a0cc0eacd1defc0985dcf6b3f17bb77dcfc8c34bec4dc5" } },
    { name = "pyyaml-6.0.2-cp312-cp312-manylinux_2_17_s390x.manylinux2014_s390x.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_s390x.manylinux2014_s390x.whl", hashes = { sha256 = "9b22676e8097e9e22e36d6b7bda33190d0d400f345f23d4065d48f4ca7ae0425" } },
    { name = "pyyaml-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hashes = { sha256 = "80bab7bfc629882493af4aa31a4cfa43a4c57c83813253626916b8c7ada83476" } },
    { name = "pyyaml-6.0.2-cp312-cp312-musllinux_1_1_aarch64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-musllinux_1_1_aarch64.whl", hashes = { sha256 = "0833f8694549e586547b576dcfaba4a6b55b9e96098b36cdc7ebefe667dfed48" } },
    { name = "pyyaml-6.0.2-cp312-cp312-musllinux_1_1_x86_64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-musllinux_1_1_x86_64.whl", hashes = { sha256 = "8b9c7197f7cb2738065c481a0461e50ad02f18c78cd75775628afb4d7137fb3b" } },
    { name = "pyyaml-6.0.2-cp312-cp312-win32.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-win32.whl", hashes = { sha256 = "ef6107725bd54b262d6dedcc2af448a266975032bc85ef0172c5f059da6325b4" } },
    { name = "pyyaml-6.0.2-cp312-cp312-win_amd64.whl", url = "https://redacted/simple/pyyaml/6.0.2/PyYAML-6.0.2-cp312-cp312-win_amd64.whl", hashes = { sha256 = "7e7401d0de89a9a855c839bc697c079a4af81cf878373abd7dc625847d25cbd8" } },
]
```

`aiofiles` successfully downloads, `pyyaml` fails.
